apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend
  # namespace: default
  # selfLink: /api/v1/namespaces/default/services/my-app-2-svc
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: frontend
